# Generated by Django 5.0.2 on 2025-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasotuvi_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
